desc "UI monkey test"
lane :unit_test do
	flag = scan(scheme: "QBFastlaneMonkeyTest",
	code_coverage: true,
	fail_build: "Test failed"
	)

	if flag 
		notification_test
	else 
		system("curl https://hooks.pubu.im/services/xm2p37x2y6zni82 -F  text=UnitTest Failed")
	end
end

lane :ui_test do
	scan(scheme: "MyUITest")
end


lane :do_build_test do

  	system("git pull origin master")
  	cocoapods
 	gym(scheme: "QBFastlaneMonkeyTest",
 		export_method: "ad-hoc",
 		output_directory: "./build"
 	)
 	end

lane :notification_test do 
	system("curl https://hooks.pubu.im/services/xm2p37x2y6zni82 -F  text=UnitTest ")
end

lane :test do
	unit_test
	notification_test
	do_build_test
end

lane :screenshot do 
	snapshot
end
